-- Nickname <-> formal-name pairs, stored pre-normalized (lowercase, unaccented)
-- so they compare directly against normalize_name() output. Lookups check
-- both directions (nickname->formal and formal->nickname).

INSERT INTO nicknames (nickname, formal) VALUES
  -- Spanish
  ('chuy', 'jesus'),
  ('chucho', 'jesus'),
  ('pepe', 'jose'),
  ('chepe', 'jose'),
  ('lupe', 'guadalupe'),
  ('lupita', 'guadalupe'),
  ('beto', 'alberto'),
  ('beto', 'roberto'),
  ('beto', 'humberto'),
  ('paco', 'francisco'),
  ('pancho', 'francisco'),
  ('lalo', 'eduardo'),
  ('tono', 'antonio'),
  ('nacho', 'ignacio'),
  ('memo', 'guillermo'),
  ('chelo', 'consuelo'),
  ('concha', 'concepcion'),
  ('conchita', 'concepcion'),
  ('meche', 'mercedes'),
  ('tere', 'teresa'),
  ('chava', 'salvador'),
  ('kike', 'enrique'),
  ('rafa', 'rafael'),
  ('mane', 'manuel'),
  ('chayo', 'rosario'),
  ('licha', 'alicia'),
  ('mari', 'maria'),
  ('juanjo', 'juan jose'),
  -- English
  ('mike', 'michael'),
  ('chris', 'christopher'),
  ('chris', 'christina'),
  ('alex', 'alexander'),
  ('alex', 'alexandra'),
  ('liz', 'elizabeth'),
  ('beth', 'elizabeth'),
  ('bill', 'william'),
  ('will', 'william'),
  ('bob', 'robert'),
  ('jim', 'james'),
  ('tony', 'anthony'),
  ('kate', 'katherine'),
  ('katie', 'katherine'),
  ('dan', 'daniel'),
  ('steve', 'steven'),
  ('steve', 'stephen'),
  ('matt', 'matthew'),
  ('nick', 'nicholas'),
  ('sam', 'samuel'),
  ('sam', 'samantha'),
  ('joe', 'joseph');
